// Top 100 films as rated by IMDb users. http://www.imdb.com/chart/top
const dummydashboardtbllist = [
  {
    Id: "",
    Checkbox: "Checkbox",
    SkuNumber: "71673",
    ItemDescription: "HERSHEYS SOYFRSH CHOC 4/946ML",
    FreightTerms: "FCL",
    SkuCount: 1,
    Moq: 0,
    SuggestedOrder: 0,
    Adjustment: 0,
    Ordered: "",
    CurrentWeekSupply: 0,
    ProjectedWeekSupply: 0,
    AdjustedWeekSupply: 0,
    NextPoArrival: "",
    PoNumber: "",
    VendorCode: "",
    VendorName: "",
    OriginalETA: "",
    UpdatedETA: "",
    CreatedOn: "",
    CreatedBy: "",
    ModifiedOn: "",
    ModifiedBy: "",
    ActionTblCol: "",
  },
  {
    Id: "",
    Checkbox: "Checkbox",
    SkuNumber: "71673",
    ItemDescription: "HERSHEYS SOYFRSH CHOC 4/946ML",
    FreightTerms: "FCL",
    SkuCount: 1,
    Moq: 0,
    SuggestedOrder: 0,
    Adjustment: 0,
    Ordered: "",
    CurrentWeekSupply: 0,
    ProjectedWeekSupply: 0,
    AdjustedWeekSupply: 0,
    NextPoArrival: "",
    PoNumber: "",
    VendorCode: "",
    VendorName: "",
    OriginalETA: "",
    UpdatedETA: "",
    CreatedOn: "",
    CreatedBy: "",
    ModifiedOn: "",
    ModifiedBy: "",
    ActionTblCol: "",
  },
  {
    Id: "",
    Checkbox: "Checkbox",
    SkuNumber: "71673",
    ItemDescription: "HERSHEYS SOYFRSH CHOC 4/946ML",
    FreightTerms: "FCL",
    SkuCount: 1,
    Moq: 0,
    SuggestedOrder: 0,
    Adjustment: 0,
    Ordered: "",
    CurrentWeekSupply: 0,
    ProjectedWeekSupply: 0,
    AdjustedWeekSupply: 0,
    NextPoArrival: "",
    PoNumber: "",
    VendorCode: "",
    VendorName: "",
    OriginalETA: "",
    UpdatedETA: "",
    CreatedOn: "",
    CreatedBy: "",
    ModifiedOn: "",
    ModifiedBy: "",
    ActionTblCol: "",
  },
  {
    Id: "",
    Checkbox: "Checkbox",
    SkuNumber: "71673",
    ItemDescription: "HERSHEYS SOYFRSH CHOC 4/946ML",
    FreightTerms: "FCL",
    SkuCount: 1,
    Moq: 0,
    SuggestedOrder: 0,
    Adjustment: 0,
    Ordered: "",
    CurrentWeekSupply: 0,
    ProjectedWeekSupply: 0,
    AdjustedWeekSupply: 0,
    NextPoArrival: "",
    PoNumber: "",
    VendorCode: "",
    VendorName: "",
    OriginalETA: "",
    UpdatedETA: "",
    CreatedOn: "",
    CreatedBy: "",
    ModifiedOn: "",
    ModifiedBy: "",
    ActionTblCol: "",
  },
  {
    Id: "",
    Checkbox: "Checkbox",
    SkuNumber: "71673",
    ItemDescription: "HERSHEYS SOYFRSH CHOC 4/946ML",
    FreightTerms: "FCL",
    SkuCount: 1,
    Moq: 0,
    SuggestedOrder: 0,
    Adjustment: 0,
    Ordered: "",
    CurrentWeekSupply: 0,
    ProjectedWeekSupply: 0,
    AdjustedWeekSupply: 0,
    NextPoArrival: "",
    PoNumber: "",
    VendorCode: "",
    VendorName: "",
    OriginalETA: "",
    UpdatedETA: "",
    CreatedOn: "",
    CreatedBy: "",
    ModifiedOn: "",
    ModifiedBy: "",
    ActionTblCol: "",
  },
  {
    Id: "",
    Checkbox: "Checkbox",
    SkuNumber: "71673",
    ItemDescription: "HERSHEYS SOYFRSH CHOC 4/946ML",
    FreightTerms: "FCL",
    SkuCount: 1,
    Moq: 0,
    SuggestedOrder: 0,
    Adjustment: 0,
    Ordered: "",
    CurrentWeekSupply: 0,
    ProjectedWeekSupply: 0,
    AdjustedWeekSupply: 0,
    NextPoArrival: "",
    PoNumber: "",
    VendorCode: "",
    VendorName: "",
    OriginalETA: "",
    UpdatedETA: "",
    CreatedOn: "",
    CreatedBy: "",
    ModifiedOn: "",
    ModifiedBy: "",
    ActionTblCol: "",
  },
  {
    Id: "",
    Checkbox: "Checkbox",
    SkuNumber: "71673",
    ItemDescription: "HERSHEYS SOYFRSH CHOC 4/946ML",
    FreightTerms: "FCL",
    SkuCount: 1,
    Moq: 0,
    SuggestedOrder: 0,
    Adjustment: 0,
    Ordered: "",
    CurrentWeekSupply: 0,
    ProjectedWeekSupply: 0,
    AdjustedWeekSupply: 0,
    NextPoArrival: "",
    PoNumber: "",
    VendorCode: "",
    VendorName: "",
    OriginalETA: "",
    UpdatedETA: "",
    CreatedOn: "",
    CreatedBy: "",
    ModifiedOn: "",
    ModifiedBy: "",
    ActionTblCol: "",
  },
];

export default dummydashboardtbllist;
